title: Alyvix
default_lang: en

author:
  name: Alyvix Team
  email: 'info@alyvix.com'

metadata:
    description: 'Alyvix: Eyes and hands like a human, with a stopwatch.'

redirects:
    'http://www.alyvix.com' : 'http://alyvix.com'
    'https://www.alyvix.com' : 'https://alyvix.com'
    '/alyvix' : '/'
    '/core' : '/'
    '/en': '/'
    '/de': '/'
    '/it': '/'
    '/synthetic-monitoring' : '/'
    '/visual-monitoring' : '/'
    '/pricing' : '/service'
    '/solution' : '/service'
    '/system-integration' : '/service'
    '/training' : '/service'
    '/about-us' : '/team'
    '/a-training-with-realstuff' : '/team'
    '/events' : '/team'
    '/osmc-2018-nuremberg' : '/team'
    '/support' : '/team'
    '/doc' : '/learn'
    '/cloud' : '/blog'
    '/hackthealps' : 'blog'
    '/hospital-scenario-distributed-monitoring-environment' : '/blog'
    '/ibb' : '/blog'
    '/success-stories' : '/blog'
    '/test-cases-on-microsoft-dynamics-ax' : '/blog'
    '/doc/test_case_execution.html' : '/learn/test_case_execution.html'
    '/doc/get_in_touch.html' : '/learn/get_in_touch.html'
    '/doc/getting_started.html' : 'learn/getting_started.html'
    '/doc/getting_started/install.html' : 'learn/getting_started/install.html'
    '/doc/test_case_building.html' : 'learn/test_case_building.html'
    '/glossary' : 'learn/glossary.html'
    '/app-availability-responsiveness' : 'learn/introduction.html'
    '/end-user-monitoring-why' : '/learn/introduction.html'
    '/linux' : '/learn/introduction.html'
    '/pervasive-monitoring' : '/learn/introduction.html'
    '/open-source' : '/learn/introduction.html'
    '/visual-synthetic-monitoring-2' : '/learn/introduction.html'
    '/2-4-1-release-notes' : '/learn/release_notes.html'
